import dataclasses as dcls
from typing import Any

from typing_extensions import Self

from bocoel.corpora.interfaces import Corpus, Distance, Embedder, Index, Storage


@dcls.dataclass(frozen=True)
class ComposedCorpus(Corpus):
    """
    Simply a collection of components.
    """

    index: Index
    storage: Storage

    @classmethod
    def index_storage(
        cls,
        storage: Storage,
        embedder: Embedder,
        key: str,
        klass: type[Index],
        distance: Distance,
        **kwargs: Any
    ) -> Self:
        """
        Creates a corpus from the given storage, embedder, key and index class.

        Parameters
        ----------

        `storage: Storage`
        Storage is used to store the questions / answers / etc.
        Can be viewed as a dataframe of texts.

        `embedder: Embedder`
        Embedder is used to embed the texts into vectors.
        It should provide the number of dims for the index to look into.

        `key: str`
        The key to the column to search over.

        `klass: type[Index]`
        The index class to use.
        Creates an index from the embeddings generated by the embedder.
        """

        embeddings = embedder.encode(storage.get(key))
        index = klass.from_embeddings(embeddings, distance=distance, **kwargs)
        return cls(index=index, storage=storage)
